// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfEMaV1RAZO7fe1Bryz6bPxckJqdPhh1k',
    appId: '1:568463691126:android:4c0d1f203c8c3d4c633e57',
    messagingSenderId: '568463691126',
    projectId: 'expense-tracker-2ad46',
    databaseURL: 'https://expense-tracker-2ad46-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-2ad46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRZtsmQw6MsX0XF31NNe-vNbuflzT2hO8',
    appId: '1:568463691126:ios:1a177d65b7936a32633e57',
    messagingSenderId: '568463691126',
    projectId: 'expense-tracker-2ad46',
    databaseURL: 'https://expense-tracker-2ad46-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-2ad46.appspot.com',
    androidClientId: '568463691126-uus0pjfqin68necfdlsir590t35fhv1a.apps.googleusercontent.com',
    iosClientId: '568463691126-4oa5nbdojbjquubce1kqoudta4corol3.apps.googleusercontent.com',
    iosBundleId: 'com.cvcenterprise.expensetracker',
  );
}
